In [1]:
import json
import pennylane as qml
import pennylane.numpy as np

In [60]:
def cirx():

    qml.CNOT([0,1])
    qml.RX(0.1,0)
    qml.CNOT([0,1])
        
    qml.adjoint(qml.IsingXX(0.1,wires=[0,1]))
    
qml.matrix(cirx)()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [6]:
qml.matrix(qml.CNOT([0,1])@qml.RX(0.1,wires=0)@qml.CNOT([0,1]))

array([[0.99875026+0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        -0.04997917j],
       [0.        +0.j        , 0.99875026+0.j        ,
        0.        -0.04997917j, 0.        +0.j        ],
       [0.        +0.j        , 0.        -0.04997917j,
        0.99875026+0.j        , 0.        +0.j        ],
       [0.        -0.04997917j, 0.        +0.j        ,
        0.        +0.j        , 0.99875026+0.j        ]])

In [7]:
qml.matrix(qml.IsingZZ(0.1,wires=[0,1]))

array([[0.99875026-0.04997917j, 0.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.99875026+0.04997917j,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.99875026+0.04997917j, 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.99875026-0.04997917j]])

In [10]:
qml.matrix(qml.CNOT([0,1])@qml.RZ(0.1,wires=1)@qml.CNOT([0,1]))

array([[0.99875026-0.04997917j, 0.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.99875026+0.04997917j,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.99875026+0.04997917j, 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.99875026-0.04997917j]])

In [11]:
qml.matrix(qml.IsingYY(0.1,wires=[0,1]))

array([[0.99875026+0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        +0.04997917j],
       [0.        +0.j        , 0.99875026+0.j        ,
        0.        -0.04997917j, 0.        +0.j        ],
       [0.        +0.j        , 0.        -0.04997917j,
        0.99875026+0.j        , 0.        +0.j        ],
       [0.        +0.04997917j, 0.        +0.j        ,
        0.        +0.j        , 0.99875026+0.j        ]])

In [66]:
def cir():
    qml.RZ(-np.pi/2,0)
    qml.RZ(-np.pi/2,1)
    qml.CNOT([0,1])
    qml.RX(0.1,0)
    qml.CNOT([0,1])
    qml.RZ(np.pi/2,0)
    qml.RZ(np.pi/2,1)
    
    qml.adjoint(qml.IsingYY(0.1,wires=[0,1]))
    
qml.matrix(cir)()

array([[ 1.00000000e+00-8.67000382e-19j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j, -1.73255552e-17+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 1.73255552e-17+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  1.00000000e+00+8.67000382e-19j]])

In [77]:
import json
import pennylane as qml
import pennylane.numpy as np

num_wires = 4
dev = qml.device("default.mixed", wires=num_wires)

@qml.qnode(dev)
def heisenberg_trotter(couplings, p, time, depth):
    """This QNode returns the final state of the spin chain after evolution for a time t, 
    under the Trotter approximation of the exponential of the Heisenberg Hamiltonian.
    
    Args:
        couplings (list(float)): 
            An array of length 4 that contains the coupling constants and the magnetic field 
            strength, in the order [J_x, J_y, J_z, h].
        p (float): The depolarization probability after each CNOT gate.
        depth (int): The Trotterization depth.
        time (float): Time during which the state evolves

    Returns:
        (numpy.tensor): The evolved quantum state.
    """
    # Put your code here #
    def myXX(J_x, wires):
        qml.CNOT(wires)
        qml.DepolarizingChannel(p,wires[1])
        qml.RX(J_x,wires[0])
        qml.CNOT(wires)
        qml.DepolarizingChannel(p,wires[1])
        
    def myYY(J_y, wires):
        qml.RZ(-np.pi/2,wires[0])
        qml.RZ(-np.pi/2,wires[1])
        qml.CNOT(wires)
        qml.DepolarizingChannel(p,wires[1])
        qml.RX(J_y,wires[0])
        qml.CNOT(wires)
        qml.DepolarizingChannel(p,wires[1])
        qml.RZ(np.pi/2,wires[0])
        qml.RZ(np.pi/2,wires[1])
        
    def myZZ(J_z, wires):
        qml.CNOT(wires)
        qml.DepolarizingChannel(p,wires[1])
        qml.RZ(J_z,wires[1])
        qml.CNOT(wires)
        qml.DepolarizingChannel(p,wires[1])
        
    Jx=couplings[0]*(-1)*2*time/depth
    Jy=couplings[1]*(-1)*2*time/depth
    Jz=couplings[2]*(-1)*2*time/depth
    h=couplings[3]*(-1)*2*time/depth

    for i in range(depth):
        myXX(Jx,[0,1])
        myXX(Jx,[1,2])
        myXX(Jx,[2,3])
        myXX(Jx,[3,0])
        myYY(Jy,[0,1])
        myYY(Jy,[1,2])
        myYY(Jy,[2,3])
        myYY(Jy,[3,0])
        myZZ(Jz,[0,1])
        myZZ(Jz,[1,2])
        myZZ(Jz,[2,3])
        myZZ(Jz,[3,0])
        qml.RX(h,0)
        qml.RX(h,1)
        qml.RX(h,2)
        qml.RX(h,3)
    
    return qml.state()


def calculate_fidelity(couplings, p, time, depth):
    """This function returns the fidelity between the final states of the noisy and
    noiseless Trotterizations of the Heisenberg models, using only CNOT and rotation gates

    Args:
        couplings (list(float)): 
            A list with the J_x, J_y, J_z and h parameters in the Heisenberg Hamiltonian, as
            defined in the problem statement.
        p (float): The depolarization probability of the depolarization gate that acts on the
                   target qubit of each CNOT gate.
        time (float): The period of time evolution simulated by the Trotterization.
        depth (int): The Trotterization depth.

    Returns:
        (float): Fidelity between final states of the noisy and noiseless Trotterizations
    """
    return qml.math.fidelity(heisenberg_trotter(couplings,0,time, depth),heisenberg_trotter(couplings,p,time,depth))




In [79]:
calculate_fidelity([1,2,1,0.3],0.05,2.5,1)

0.33723981062939895

In [ ]:
# These functions are responsible for testing the solution.
def run(test_case_input: str) -> str:

    ins = json.loads(test_case_input)
    output =calculate_fidelity(*ins)

    return str(output)

def check(solution_output: str, expected_output: str) -> None:
    """
    Compare solution with expected.

    Args:
            solution_output: The output from an evaluated solution. Will be
            the same type as returned.
            expected_output: The correct result for the test case.

    Raises: 
            ``AssertionError`` if the solution output is incorrect in any way.
            
    """
    def create_hamiltonian(params):

        couplings = [-params[-1]]
        ops = [qml.PauliX(3)]

        for i in range(3):

            couplings = [-params[-1]] + couplings
            ops = [qml.PauliX(i)] + ops        

        for i in range(4):

            couplings = [-params[-2]] + couplings
            ops = [qml.PauliZ(i)@qml.PauliZ((i+1)%4)] + ops

        for i in range(4):

            couplings = [-params[-3]] + couplings
            ops = [qml.PauliY(i)@qml.PauliY((i+1)%4)] + ops

        for i in range(4):

            couplings = [-params[0]] + couplings
            ops = [qml.PauliX(i)@qml.PauliX((i+1)%4)] + ops    

        return qml.Hamiltonian(couplings,ops)

    @qml.qnode(dev)
    def evolve(params, time, depth):

        qml.ApproxTimeEvolution(create_hamiltonian(params), time, depth)

        return qml.state()
    
    solution_output = json.loads(solution_output)
    expected_output = json.loads(expected_output)
    
    tape = heisenberg_trotter.qtape
    names = [op.name for op in tape.operations]
    
    random_params = np.random.uniform(low = 0.8, high = 3.0, size = (4,) )
    
    assert qml.math.fidelity(heisenberg_trotter(random_params,0,1,2),evolve(random_params,1,2)) >= 1, "Your circuit does not Trotterize the Heisenberg Model"
    
    assert names.count('ApproxTimeEvolution') == 0, "Your circuit must not use the built-in PennyLane Trotterization"
     
    assert set(names) == {'DepolarizingChannel', 'RX', 'RY', 'RZ', 'CNOT'}, "Your circuit must only use RX, RY, RZ, CNOT, and depolarizing gates (don't use qml.Rot or Paulis)"
    
    assert solution_output >= expected_output-0.005, "Your fidelity is not high enough. You may be using more CNOT gates than needed"


test_cases = [['[[1,2,1,0.3],0.05,2.5,1]', '0.33723981123369573'], ['[[1,3,2,0.3],0.05,2.5,2]', '0.15411351752086694']]

for i, (input_, expected_output) in enumerate(test_cases):
    print(f"Running test case {i} with input '{input_}'...")

    try:
        output = run(input_)

    except Exception as exc:
        print(f"Runtime Error. {exc}")

    else:
        if message := check(output, expected_output):
            print(f"Wrong Answer. Have: '{output}'. Want: '{expected_output}'.")

        else:
            print("Correct!")